export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADDNOTES_SUCCESS = "ADDNOTES_SUCCESS";
export const ADDNOTES_START = "ADDNOTES_START";
export const ADDNOTES_FAIL = "ADDNOTES_FAIL";
