export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS";
export const ADD_NOTES_START = "ADD_NOTES_START";
export const ADD_NOTES_FAIL = "ADD_NOTES_FAIL";

export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_START = "FETCH_NOTES_START";
export const FETCH_NOTES_FAIL = "FETCH_NOTES_FAIL";

export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS";
export const DELETE_NOTES_START = "DELETE_NOTES_START";
export const DELETE_NOTES_FAIL = "DELETE_NOTES_FAIL";

export const EDIT_NOTES_SUCCESS = "EDIT_NOTES_SUCCESS";
export const EDIT_NOTES_START = "EDIT_NOTES_START";
export const EDIT_NOTES_FAIL = "EDIT_NOTES_FAIL";
